### ISSUE TITLE
wrong number of types of arguments in call to 'JSON_VALUE'

### ISSUE THREAD

**Issue by FeridAbbasov** [doberkofler/PLSQL-JSON#10]
Hi! 
After installing your last plsql-json release into database appear invalid object:
JSON_EXT
and  gives error: 
24 wrong number of types of arguments in call to 'JSON_VALUE'
358 component 'MAKENULL' must be declared
374 component 'MAKENAME' must be declared

Where is the problem?

**Comment by doberkofler** [comment]
Could you provide me with a small working example of your problem?
