### ISSUE TITLE
Add a way to enable/disable conversion of chars to ascii codes

### ISSUE THREAD

**Issue by L-VV** [doberkofler/PLSQL-JSON#11]
Thank you very much for your great work!

Can you, please, add the possibility to change the behavior of private functions json_utils.escape and json_utils.escapeLOB?

It will be very-very nice if we could set theAsciiOutput := TRUE or FALSE and some other settings in a caller code, as it made in PL/JSON's json_printer package:

indent_string varchar2(10 char) := '  '; --chr(9); for tab
**newline_char** varchar2(2 char)   := chr(13)||chr(10); -- Windows style
--newline_char varchar2(2) := chr(10); -- Mac style
--newline_char varchar2(2) := chr(13); -- Linux style
**ascii_output** boolean    not null := true;
escape_solidus boolean  not null := false;

Thank you!

**Comment by doberkofler** [comment]
Version 0.6.0 now has configuration options that allow to set the `AsciiOutput` option.
A configuration option for the newline character will follow soon.

**Comment by doberkofler** [comment]
Version 0.7.0 now has two new output options: `newline_char` for the end of line style and `indentation_char` for the indentation style.
