### ISSUE TITLE
keyword with a dash throws an error

### ISSUE THREAD

**Issue by michaelachrist** [doberkofler/PLSQL-JSON#2]
Hi:
I have a keyword "item-1", and when I attempt to get the value, I receive the error: "Path parse error: expected . or [ found - at position 6"

Can anyone suggest how I can handle this?

Thanks.

**Comment by doberkofler** [comment]
Could you please post a complete example of the failing code.

**Comment by doberkofler** [comment]
@michaelachrist Closed without proper example
