### ISSUE TITLE
Unable to upload base64 image-- 

### ISSUE THREAD

**Issue by rahulwali** [doberkofler/PLSQL-JSON#4]
Hello:
I need to upload base64 image by using oracle apex web services , currently  using  PLSQL-JSON package.. I am able to upload upto 25kb that means around 3 lac characters, however my requirement my is approx is 525KB. Please help .. what are the changes that needs to be done in the package ?

Regards
Rahul

**Comment by doberkofler** [comment]
@rahulwali I've just release a version that has support for CLOB properties.
